services:
  db:
    ports:
      - 5432:5432
  ui:
    networks:
      - internal
    volumes:
      - ./equipment-reservation-ui/:/app
      - /app/node_modules
    build:
      context: ./equipment-reservation-ui
      dockerfile: Dockerfile.dev
  inventory:
    networks:
      - internal
    volumes:
      - ./Inventory/Inventory/:/app
      - /app/bin
      - /app/obj
    build:
      context: ./Inventory/Inventory
      dockerfile: DockerfileDev
  reservation:
    networks:
      - internal
    volumes:
      - ./Reservation/Reservation/:/app
      - /app/bin
      - /app/obj
    build:
      context: ./Reservation/Reservation
      dockerfile: DockerfileDev
networks:
  internal:
  public:
