services:
  pocket-id:
    image: pocketid/pocket-id:v2
    restart: unless-stopped
    networks:
      - internal
    env_file: .env
    ports:
      - 1411:1411
    volumes:
      - "./pocket-id:/app/data"
  caddy:
    image: caddy
    restart: unless-stopped
    networks:
      - public
      - internal
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/conf:/etc/caddy
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
  ui:
    networks:
      - internal
    build:
      context: ./equipment-reservation-ui
      dockerfile: Dockerfile
  inventory:
    restart: always
    depends_on:
      - db
    networks:
      - internal
    build:
      context: ./Inventory/Inventory
      dockerfile: Dockerfile
    environment:
      Inventory__DatabaseUrl: Host=db;Port=5432;Database=inventory;Username=admin;Password=admin
  reservation:
    restart: always
    depends_on:
      - db
    networks:
      - internal
    build:
      context: ./Reservation/Reservation
      dockerfile: Dockerfile
    environment:
      Reservation__DatabaseUrl: Host=db;Port=5432;Database=reservation;Username=admin;Password=admin
      Reservation__InventoryServiceUrl: http://inventory:8080
      Reservation__InventorySubAddr: tcp://inventory:5556
  db:
    networks:
      - internal
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: inventory
networks:
  internal:
    driver: bridge
    internal: true
  public:
    driver: bridge
volumes:
  caddy_data:
  caddy_config:
