services:
  inventory:
    build:
      context: ./inventory/
      dockerfile: ./Dockerfile
    image: inventory
  reservation:
    environment:
      INVENTORY_ENDPOINT: "http://inventory:3000"
    build:
      context: ./reservation/
      dockerfile: ./Dockerfile
    image: reservation
