services:
  pocket-id:
    image: pocketid/pocket-id:v2
    restart: unless-stopped
    networks:
      - internal
    env_file: .env
    ports:
      - 1411:1411
    volumes:
      - "./pocket-id:/app/data"
  caddy:
    image: caddy
    restart: unless-stopped
    networks:
      public:
      internal:
        aliases:
          - auth.equipment.localhost
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/conf:/etc/caddy
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
  ui:
    networks:
      - internal
    build:
      context: ./equipment-reservation-ui
      dockerfile: Dockerfile
  inventory:
    restart: always
    depends_on:
      - db
    networks:
      - internal
    build:
      context: ./Inventory/Inventory
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__InventoryDb: Host=db;Port=5432;Database=inventory;Username=admin;Password=admin
      Inventory__JwtAuthority: https://auth.equipment.localhost
      Inventory__JwtAudience: ba0dcb0e-eb13-4bcd-8e68-4552ae88aa36
      Inventory__ReservationSubAddr: tcp://reservation:5557
      OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire:18889
      OTEL_SERVICE_NAME: "Inventory"
  reservation:
    restart: always
    depends_on:
      - db
    networks:
      - internal
    build:
      context: ./Reservation/Reservation
      dockerfile: Dockerfile
    environment:
      Reservation__DatabaseUrl: Host=db;Port=5432;Database=reservation;Username=admin;Password=admin
      Reservation__InventoryServiceUrl: http://inventory:8080
      Reservation__InventorySubAddr: tcp://inventory:5556
      Reservation__JwtAuthority: https://auth.equipment.localhost
      Reservation__JwtAudience: ba0dcb0e-eb13-4bcd-8e68-4552ae88aa36
      OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire:18889
      OTEL_SERVICE_NAME: "Reservation"
  db:
    networks:
      - internal
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
  aspire:
    networks:
      - internal
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    environment:
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: true
      ASPIRE_ALLOW_UNSECURED_TRANSPORT: true
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
networks:
  internal:
    driver: bridge
    internal: true
  public:
    driver: bridge
volumes:
  caddy_data:
  caddy_config:
