services:
  tinyauth:
    image: ghcr.io/tinyauthapp/tinyauth:v5
    networks:
      - internal
    restart: unless-stopped
    volumes:
      - ./tinyauth_data:/data
    environment:
      - TINYAUTH_APPURL=https://auth.equipment.localhost
      - TINYAUTH_AUTH_USERS=admin:$$2b$$10$$zOkDdAK2YBM1zEzEXIOrGOixr3gZdvNB7Rz8dBYF1Xbc0/wU8hFRq
      - TINYAUTH_OIDC_CLIENTS_EQUIPMENT_CLIENTID=420a32cb-5100-4bee-b770-e273e059e326
      - TINYAUTH_OIDC_CLIENTS_EQUIPMENT_CLIENTSECRET=ta-KaONTC5Fq0cvH8YiOJhmdjoLPU9EZpQ3AHTmStjMJ5sunvdvQifCoYo5C3FLd
      - TINYAUTH_OIDC_CLIENTS_EQUIPMENT_NAME=Equipment
      - TINYAUTH_OIDC_CLIENTS_EQUIPMENT_TRUSTEDREDIRECTURIS=https://equipment.localhost
  caddy:
    image: caddy
    restart: unless-stopped
    networks:
      - public
      - internal
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/conf:/etc/caddy
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
  ui:
    networks:
      - internal
    build:
      context: ./equipment-reservation-ui
      dockerfile: Dockerfile
networks:
  internal:
    driver: bridge
    internal: true
  public:
    driver: bridge
volumes:
  caddy_data:
  caddy_config:
