@Inventory_HostAddress = http://localhost:5058

GET {{Inventory_HostAddress}}/openapi/v1.json
Accept: application/json

####

POST {{Inventory_HostAddress}}/api/v1/Equipment
Accept: application/json
Content-Type: application/json

{
    "name": "asdfaserase asdfasdf asdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaseraseasdfaserase",
    "description": null
}
