@Reservation_HostAddress = http://localhost:5264

GET {{Reservation_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{Reservation_HostAddress}}/weatherforecast/
Accept: application/json

###
